config/routes.rb
Books::Application.routes.draw do
  resources :logins

  match '/show', to: 'search#show'
  resources :searches

  resources :books
  resources :users
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :category,:available , :dueDate, :email, :firstName, :lastName, :password, :signOut, :Bookname, :userName
validates :firstName,:lastName,:email,:userName,:password,:presence => true

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
   def index
    @books = Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  
  def new
    @book = Book.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
    WelcomeMailer.signup("nik_g2@hotmail.com").deliver
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])
  
    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
        WelcomeMailer.signup("nik_g2@hotmail.com").deliver
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  
end

app/views/users/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstName %><br />
    <%= f.text_field :firstName %>
  </div>
  <div class="field">
    <%= f.label :lastName %><br />
    <%= f.text_field :lastName %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :userName %><br />
    <%= f.text_field :userName %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.number_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div id="wrapper">
		<div id="header">
			<div id="logo">
				<img src="/assets/logo.png" />
			</div>
			<div id="headerContent">
				<div id="headerContentTop">
					<a href="#">User</a> | <a href="#">Admin</a>
				</div>
				<div id="headerContentBottom">
					<h1>My Dashboard</h1>
					<h3>User Accounts</h3>
				</div>
			</div>
</div>
		<div id="mainContent">
			<div id="mainContent-left">
				<h3>All Users:</h3>
				<div id="dashboard">
					<table >
					  <tr>
					    <th>First name</th>
					    <th>Last name</th>
					    <th>Email</th>
					    <th>User name</th>
					    <th>User type</th>
					    
					    <th></th>
					    <th></th>
					  </tr>
					
					<% @books.each do |book| %>
						<% if book.category ==1 || book.category==2%>
					  <tr>
					    <td><%= book.firstName %></td>
					    <td><%= book.lastName %></td>
					    <td><%= book.email %></td>
					    <td><%= book.userName %></td>
					    
					    <% if book.category ==1 %>
					    	<td>Admin</td>
					    <% end %>
					    <% if book.category ==2%>
					    	<td>User </td>
					    	<% end %>
					    
					    <td><%= link_to 'Edit', edit_user_path(book) %></td>
					    <td><%= link_to 'Remove account', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
					  </tr>
					  <% end%>
					<% end %>
					</table>
				</div>
			</div>
			<div id="mainContent-right">
				<h2>What would you like to do?</h2>
				<ul>
					<li><%= link_to 'New User', new_user_path %></li>
					<li><%= link_to 'View Sign outs', books_path%></li>
					<li><%= link_to 'Search', searches_path %></li>
				</ul>
			</div>
			
		</div>
		<div id="footer">
			<p>&#0169; Cloud Library 2013</p>
		</div>
	</div>

app/views/users/new.html.erb
<div id="wrapper">
		<div id="header">
			<div id="logo">
				<img src="/assets/logo.png" />
			</div>
			<div id="headerContent">
				<div id="headerContentTop">
					<a href="#">User</a> | <a href="#">Admin</a>
				</div>
				<div id="headerContentBottom">
					<h1>My Dashboard</h1>
					<h3>Checked Outs</h3>
				</div>
			</div>
</div>
		<div id="mainContent">
			<div id="mainContentTop-form">
				<h3>Sign Up:</h3>
				<%= form_for(@book) do |f| %>
				  <% if @book.errors.any? %>
				    <div id="error_explanation">
				      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
				
				      <ul>
				      <% @book.errors.full_messages.each do |msg| %>
				        <li><%= msg %></li>
				      <% end %>
				      </ul>
				    </div>
				  <% end %>
				
				  <div class="field">
				    <%= f.label "First name" %><br />
				    <%= f.text_field :firstName %>
				  </div>
				  <div class="field">
				    <%= f.label "Last name" %><br />
				    <%= f.text_field :lastName %>
				  </div>
				
				  <div class="field">
				    <%= f.label "Email address" %><br />
				    <%= f.text_field :email %>
				  </div>
				  <div class="field">
				    <%= f.label "User name" %><br />
				    <%= f.text_field :userName %>
				  </div>
				  <div class="field">
				    <%= f.label "Password" %><br />
				    <%= f.text_field :password %>
				  </div>
				  <div class="field">
				    <%= f.label :category %><br />
				    <%= f.number_field :category, :value =>'2',:readonly=>true %>
				  </div>
				  
				  <div class="actions">
				    <%= f.submit "Create Account" %>
				  </div>
				<% end %>
					<%= link_to 'Back', users_path %>

			</div>
			
		</div>
		<div id="footer">
			<p>&#0169; Cloud Library 2013</p>
		</div>
	</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Book Name:</b>
  <%= @book.Bookname%>
</p>

<p>
  <b>Category:</b>
  <%= @book.category %>
</p>



<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>