config/routes.rb
Books::Application.routes.draw do
  resources :logins

  match '/show', to: 'search#show'
  resources :searches

  resources :books
  resources :users
  

end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :category, :dueDate, :email, :firstName, :lastName, :password, :signOut,:available ,:Bookname, :userName
validates :firstName,:lastName,:email,:userName,:password,:presence => true
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  # GET /books.json
  def index
    @books = Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      WelcomeMailer.signup("nik_g2@hotmail.com").deliver
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to searches_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<div id="wrapper">
		<div id="header">
			<div id="logo">
				<img src="/assets/logo.png" />
			</div>
			<div id="headerContent">
				<div id="headerContentTop">
					<a href="#">User</a> | <a href="#">Admin</a>
				</div>
				<div id="headerContentBottom">
					<h1>My Dashboard</h1>
					<h3>Checked Outs</h3>
				</div>
			</div>
</div>
		<div id="mainContent">
			<div id="mainContentTop-form">
				<h3>Add a new book:</h3>
				<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstName %><br />
    <%= f.text_field :firstName %>
  </div>
  <div class="field">
    <%= f.label :lastName %><br />
    <%= f.text_field :lastName %>
  </div>
  <div class="field">
    <%= f.label :Bookname%><br />
    <%= f.text_field :Bookname %>
  </div>
  <div class="field">
    <%= f.label :signOut %><br />
    <%= f.date_select :signOut %>
  </div>
  <div class="field">
    <%= f.label :dueDate %><br />
    <%= f.date_select :dueDate %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :userName %><br />
    <%= f.text_field :userName %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.number_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
			</div>
			
		</div>
		<div id="footer">
			<p>&#0169; Cloud Library 2013</p>
		</div>
	</div>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<div id="wrapper">
		<div id="header">
			<div id="logo">
				<img src="/assets/logo.png" />
			</div>
			<div id="headerContent">
				<div id="headerContentTop">
					<a href="#">User</a> | <a href="#">Admin</a>
				</div>
				<div id="headerContentBottom">
					<h1>My Dashboard</h1>
					<h3>Checked Outs</h3>
				</div>
			</div>
</div>
		<div id="mainContent">
			<div id="mainContent-left">
				<h3>Checked out books:</h3>
				<div id="dashboard">
					<table valign="middle">
						  <tr>
						    <th>First name&nbsp&nbsp</th>
						    <th>Last name&nbsp&nbsp</th>
						    <th>Sign out&nbsp&nbsp</th>
						    <th>Due date&nbsp&nbsp</th>
						    <th>Email&nbsp&nbsp</th>
						    <th>User name&nbsp&nbsp</th>
						    
						    <th>Sign out/On hold&nbsp&nbsp</th>
						    <th>Book Title&nbsp&nbsp</th>
						    <th></th>
						  </tr>
						
						<% @books.each do |book| %>
						<% if book.category == 4 || book.category ==5 %>
						  <tr>
						    <td><%= book.firstName %></td>
						    <td><%= book.lastName %></td>
						    <td><%= book.signOut %></td>
						    <td><%= book.dueDate %></td>
						    <td><%= book.email %></td>
						    <td><%= book.userName %></td>
						    <%if book.category ==4%>
						    <td>Sign out</td>
						    <%end%>
						    <%if book.category ==5%>
						    <td>On hold</td>
						    <%end%>
						    <td><%= book.Bookname %></td>
						    
						    <td><%= link_to 'Return', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
						  </tr>
						  <% end%>
						<% end %>
						</table>
				</div>
			</div>
			<div id="mainContent-right">
				<h2>What would you like to do?</h2>
				<ul>
					<li><%= link_to 'New Book', new_book_path %></li>
					<li><%= link_to 'User Accounts',users_path%></li>
					<li><%= link_to 'Search', searches_path %></li>
				</ul>
			</div>
			
		</div>
		<div id="footer">
			<p>&#0169; Cloud Library 2013</p>
		</div>
	</div>

app/views/books/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Firstname:</b>
  <%= @book.firstName %>
</p>

<p>
  <b>Lastname:</b>
  <%= @book.lastName %>
</p>

<p>
  <b>Signout:</b>
  <%= @book.signOut %>
</p>

<p>
  <b>Duedate:</b>
  <%= @book.dueDate %>
</p>

<p>
  <b>Email:</b>
  <%= @book.email %>
</p>

<p>
  <b>Username:</b>
  <%= @book.userName %>
</p>

<p>
  <b>Password:</b>
  <%= @book.password %>
</p>

<p>
  <b>Category:</b>
  <%= @book.category %>
</p>


<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>