config/routes.rb
Books::Application.routes.draw do
  resources :logins

  match '/show', to: 'search#show'
  resources :searches

  resources :books
  resources :users
  

end

app/models/search.rb
class Search < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :category, :dueDate, :email,:available , :firstName, :lastName, :password, :signOut, :Bookname, :userName
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  # GET /searches
  # GET /searches.json
  def index
    @books = Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new
    redirect_to :searches
    
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to searches_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstName %><br />
    <%= f.text_field :firstName %>
  </div>
  <div class="field">
    <%= f.label :lastName %><br />
    <%= f.text_field :lastName %>
  </div>
  <div class="field">
    <%= f.label :Bookname%><br />
    <%= f.text_field :Bookname %>
  </div>
  <div class="field">
    <%= f.label :signOut %><br />
    <%= f.date_select :signOut %>
  </div>
  <div class="field">
    <%= f.label :dueDate %><br />
    <%= f.date_select :dueDate %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :userName %><br />
    <%= f.text_field :userName %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.number_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/searches/edit.html.erb
<h1>Edit book</h1>

<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.label :Bookname %><br />
    <%= f.text_field :Bookname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Show', @book %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<div id="wrapper">
		<div id="header">
			<div id="logo">
				<img src="/assets/logo.png" />
			</div>
			<div id="headerContent">
				<div id="headerContentTop">
					<a href="#">User</a> | <a href="#">Admin</a>
				</div>
				<div id="headerContentBottom">
					<h1>My Dashboard</h1>
					<h3>Browse Books</h3>
				</div>
			</div>
</div>
		<div id="mainContent">
			<div id="mainContent-left">
				<h3>Available Books:</h3>
				<div id="dashboard">
					<table>
				  		<tr>
						    <th>Book Title</th>
						    <th></th>
						    <th></th>
				 		 </tr>
				
						<% @books.each do |book| %>
							<% if book.category == 3  %>
						 		 <tr>
						    		 <td><%= book.Bookname %></td>
						    		 <td><%= link_to 'Edit book details', edit_search_path(book) %></td>
						   			 <td><%= link_to 'Remove book', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
						  		</tr>
					   		<% end%>
						<% end %>
				</table>
				</div>
			</div>
			<div id="mainContent-right">
				<h2>What would you like to do?</h2>
				<ul>
					<li><%= link_to 'Books', books_path %></li>
					<li><%= link_to 'User Accounts',users_path%></li>
					<li><%= link_to 'Search', searches_path %></li>
				</ul>
			</div>
			
		</div>
		<div id="footer">
			<p>&#0169; Cloud Library 2013</p>
		</div>
	</div>

				

app/views/searches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Book Name:</b>
  <%= @book.Bookname%>
</p>

<p>
  <b>Category:</b>
  <%= @book.category %>
</p>


<%= link_to 'Edit', edit_search_path(@book) %> |
<%= link_to 'Back', searches_path %>